language: python
os:
  - linux
python:
  - 3.6
install:
  - pip install -r ./pip/requirements.txt
script:
  - python vulnx.py -l
  - python vulnx.py -u www.google.com -t 3 -d -w
  - python3 vulnx.py -D blaze -n 5